/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './root';
import { Route as FeaturesShellPagesUnauthenticatedLayoutImport } from './features/shell/pages/unauthenticated-layout';
import { Route as FeaturesShellPagesAuthenticatedLayoutImport } from './features/shell/pages/authenticated-layout';
import { Route as FeaturesSettingsPagesIndexImport } from './features/settings/pages/index';
import { Route as FeaturesAuthPagesLoginPageImport } from './features/auth/pages/login-page';
import { Route as FeaturesProductPagesProductPageImport } from './features/product/pages/product-page';
import { Route as FeaturesHomePagesHomeImport } from './features/home/pages/home';
import { Route as FeaturesProductPagesUpdateProductPageImport } from './features/product/pages/update-product-page';
import { Route as FeaturesAccountPagesAccountProfilePageImport } from './features/account/pages/account-profile-page';

// Create/Update Routes

const FeaturesShellPagesUnauthenticatedLayoutRoute =
  FeaturesShellPagesUnauthenticatedLayoutImport.update({
    id: '/_(unauthenticated)',
    getParentRoute: () => rootRoute,
  } as any);

const FeaturesShellPagesAuthenticatedLayoutRoute =
  FeaturesShellPagesAuthenticatedLayoutImport.update({
    id: '/_(authenticated)',
    getParentRoute: () => rootRoute,
  } as any);

const FeaturesSettingsPagesIndexRoute = FeaturesSettingsPagesIndexImport.update(
  {
    id: '/settings',
    path: '/settings',
    getParentRoute: () => FeaturesShellPagesAuthenticatedLayoutRoute,
  } as any,
);

const FeaturesAuthPagesLoginPageRoute = FeaturesAuthPagesLoginPageImport.update(
  {
    id: '/login',
    path: '/login',
    getParentRoute: () => FeaturesShellPagesUnauthenticatedLayoutRoute,
  } as any,
);

const FeaturesProductPagesProductPageRoute =
  FeaturesProductPagesProductPageImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => FeaturesShellPagesAuthenticatedLayoutRoute,
  } as any);

const FeaturesHomePagesHomeRoute = FeaturesHomePagesHomeImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeaturesShellPagesAuthenticatedLayoutRoute,
} as any);

const FeaturesProductPagesUpdateProductPageRoute =
  FeaturesProductPagesUpdateProductPageImport.update({
    id: '/product/$productId',
    path: '/product/$productId',
    getParentRoute: () => FeaturesShellPagesAuthenticatedLayoutRoute,
  } as any);

const FeaturesAccountPagesAccountProfilePageRoute =
  FeaturesAccountPagesAccountProfilePageImport.update({
    id: '/account/profile',
    path: '/account/profile',
    getParentRoute: () => FeaturesSettingsPagesIndexRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_(authenticated)': {
      id: '/_(authenticated)';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof FeaturesShellPagesAuthenticatedLayoutImport;
      parentRoute: typeof rootRoute;
    };
    '/_(unauthenticated)': {
      id: '/_(unauthenticated)';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof FeaturesShellPagesUnauthenticatedLayoutImport;
      parentRoute: typeof rootRoute;
    };
    '/_(authenticated)/': {
      id: '/_(authenticated)/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof FeaturesHomePagesHomeImport;
      parentRoute: typeof FeaturesShellPagesAuthenticatedLayoutImport;
    };
    '/_(authenticated)/products': {
      id: '/_(authenticated)/products';
      path: '/products';
      fullPath: '/products';
      preLoaderRoute: typeof FeaturesProductPagesProductPageImport;
      parentRoute: typeof FeaturesShellPagesAuthenticatedLayoutImport;
    };
    '/_(unauthenticated)/login': {
      id: '/_(unauthenticated)/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof FeaturesAuthPagesLoginPageImport;
      parentRoute: typeof FeaturesShellPagesUnauthenticatedLayoutImport;
    };
    '/_(authenticated)/settings': {
      id: '/_(authenticated)/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof FeaturesSettingsPagesIndexImport;
      parentRoute: typeof FeaturesShellPagesAuthenticatedLayoutImport;
    };
    '/_(authenticated)/product/$productId': {
      id: '/_(authenticated)/product/$productId';
      path: '/product/$productId';
      fullPath: '/product/$productId';
      preLoaderRoute: typeof FeaturesProductPagesUpdateProductPageImport;
      parentRoute: typeof FeaturesShellPagesAuthenticatedLayoutImport;
    };
    '/_(authenticated)/settings/account/profile': {
      id: '/_(authenticated)/settings/account/profile';
      path: '/account/profile';
      fullPath: '/settings/account/profile';
      preLoaderRoute: typeof FeaturesAccountPagesAccountProfilePageImport;
      parentRoute: typeof FeaturesSettingsPagesIndexImport;
    };
  }
}

// Create and export the route tree

interface FeaturesSettingsPagesIndexRouteChildren {
  FeaturesAccountPagesAccountProfilePageRoute: typeof FeaturesAccountPagesAccountProfilePageRoute;
}

const FeaturesSettingsPagesIndexRouteChildren: FeaturesSettingsPagesIndexRouteChildren =
  {
    FeaturesAccountPagesAccountProfilePageRoute:
      FeaturesAccountPagesAccountProfilePageRoute,
  };

const FeaturesSettingsPagesIndexRouteWithChildren =
  FeaturesSettingsPagesIndexRoute._addFileChildren(
    FeaturesSettingsPagesIndexRouteChildren,
  );

interface FeaturesShellPagesAuthenticatedLayoutRouteChildren {
  FeaturesHomePagesHomeRoute: typeof FeaturesHomePagesHomeRoute;
  FeaturesProductPagesProductPageRoute: typeof FeaturesProductPagesProductPageRoute;
  FeaturesSettingsPagesIndexRoute: typeof FeaturesSettingsPagesIndexRouteWithChildren;
  FeaturesProductPagesUpdateProductPageRoute: typeof FeaturesProductPagesUpdateProductPageRoute;
}

const FeaturesShellPagesAuthenticatedLayoutRouteChildren: FeaturesShellPagesAuthenticatedLayoutRouteChildren =
  {
    FeaturesHomePagesHomeRoute: FeaturesHomePagesHomeRoute,
    FeaturesProductPagesProductPageRoute: FeaturesProductPagesProductPageRoute,
    FeaturesSettingsPagesIndexRoute:
      FeaturesSettingsPagesIndexRouteWithChildren,
    FeaturesProductPagesUpdateProductPageRoute:
      FeaturesProductPagesUpdateProductPageRoute,
  };

const FeaturesShellPagesAuthenticatedLayoutRouteWithChildren =
  FeaturesShellPagesAuthenticatedLayoutRoute._addFileChildren(
    FeaturesShellPagesAuthenticatedLayoutRouteChildren,
  );

interface FeaturesShellPagesUnauthenticatedLayoutRouteChildren {
  FeaturesAuthPagesLoginPageRoute: typeof FeaturesAuthPagesLoginPageRoute;
}

const FeaturesShellPagesUnauthenticatedLayoutRouteChildren: FeaturesShellPagesUnauthenticatedLayoutRouteChildren =
  {
    FeaturesAuthPagesLoginPageRoute: FeaturesAuthPagesLoginPageRoute,
  };

const FeaturesShellPagesUnauthenticatedLayoutRouteWithChildren =
  FeaturesShellPagesUnauthenticatedLayoutRoute._addFileChildren(
    FeaturesShellPagesUnauthenticatedLayoutRouteChildren,
  );

export interface FileRoutesByFullPath {
  '': typeof FeaturesShellPagesUnauthenticatedLayoutRouteWithChildren;
  '/': typeof FeaturesHomePagesHomeRoute;
  '/products': typeof FeaturesProductPagesProductPageRoute;
  '/login': typeof FeaturesAuthPagesLoginPageRoute;
  '/settings': typeof FeaturesSettingsPagesIndexRouteWithChildren;
  '/product/$productId': typeof FeaturesProductPagesUpdateProductPageRoute;
  '/settings/account/profile': typeof FeaturesAccountPagesAccountProfilePageRoute;
}

export interface FileRoutesByTo {
  '': typeof FeaturesShellPagesUnauthenticatedLayoutRouteWithChildren;
  '/': typeof FeaturesHomePagesHomeRoute;
  '/products': typeof FeaturesProductPagesProductPageRoute;
  '/login': typeof FeaturesAuthPagesLoginPageRoute;
  '/settings': typeof FeaturesSettingsPagesIndexRouteWithChildren;
  '/product/$productId': typeof FeaturesProductPagesUpdateProductPageRoute;
  '/settings/account/profile': typeof FeaturesAccountPagesAccountProfilePageRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/_(authenticated)': typeof FeaturesShellPagesAuthenticatedLayoutRouteWithChildren;
  '/_(unauthenticated)': typeof FeaturesShellPagesUnauthenticatedLayoutRouteWithChildren;
  '/_(authenticated)/': typeof FeaturesHomePagesHomeRoute;
  '/_(authenticated)/products': typeof FeaturesProductPagesProductPageRoute;
  '/_(unauthenticated)/login': typeof FeaturesAuthPagesLoginPageRoute;
  '/_(authenticated)/settings': typeof FeaturesSettingsPagesIndexRouteWithChildren;
  '/_(authenticated)/product/$productId': typeof FeaturesProductPagesUpdateProductPageRoute;
  '/_(authenticated)/settings/account/profile': typeof FeaturesAccountPagesAccountProfilePageRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | ''
    | '/'
    | '/products'
    | '/login'
    | '/settings'
    | '/product/$productId'
    | '/settings/account/profile';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | ''
    | '/'
    | '/products'
    | '/login'
    | '/settings'
    | '/product/$productId'
    | '/settings/account/profile';
  id:
    | '__root__'
    | '/_(authenticated)'
    | '/_(unauthenticated)'
    | '/_(authenticated)/'
    | '/_(authenticated)/products'
    | '/_(unauthenticated)/login'
    | '/_(authenticated)/settings'
    | '/_(authenticated)/product/$productId'
    | '/_(authenticated)/settings/account/profile';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  FeaturesShellPagesAuthenticatedLayoutRoute: typeof FeaturesShellPagesAuthenticatedLayoutRouteWithChildren;
  FeaturesShellPagesUnauthenticatedLayoutRoute: typeof FeaturesShellPagesUnauthenticatedLayoutRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  FeaturesShellPagesAuthenticatedLayoutRoute:
    FeaturesShellPagesAuthenticatedLayoutRouteWithChildren,
  FeaturesShellPagesUnauthenticatedLayoutRoute:
    FeaturesShellPagesUnauthenticatedLayoutRouteWithChildren,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "root.tsx",
      "children": [
        "/_(authenticated)",
        "/_(unauthenticated)"
      ]
    },
    "/_(authenticated)": {
      "filePath": "./features/shell/pages/authenticated-layout.tsx",
      "children": [
        "/_(authenticated)/",
        "/_(authenticated)/products",
        "/_(authenticated)/settings",
        "/_(authenticated)/product/$productId"
      ]
    },
    "/_(unauthenticated)": {
      "filePath": "./features/shell/pages/unauthenticated-layout.tsx",
      "children": [
        "/_(unauthenticated)/login"
      ]
    },
    "/_(authenticated)/": {
      "filePath": "./features/home/pages/home.tsx",
      "parent": "/_(authenticated)"
    },
    "/_(authenticated)/products": {
      "filePath": "./features/product/pages/product-page.tsx",
      "parent": "/_(authenticated)"
    },
    "/_(unauthenticated)/login": {
      "filePath": "./features/auth/pages/login-page.tsx",
      "parent": "/_(unauthenticated)"
    },
    "/_(authenticated)/settings": {
      "filePath": "./features/settings/pages/index.tsx",
      "parent": "/_(authenticated)",
      "children": [
        "/_(authenticated)/settings/account/profile"
      ]
    },
    "/_(authenticated)/product/$productId": {
      "filePath": "./features/product/pages/update-product-page.tsx",
      "parent": "/_(authenticated)"
    },
    "/_(authenticated)/settings/account/profile": {
      "filePath": "./features/account/pages/account-profile-page.tsx",
      "parent": "/_(authenticated)/settings"
    }
  }
}
ROUTE_MANIFEST_END */
