version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dungcool102608@
      POSTGRES_DB: orbit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
    container_name: nest-app
    restart: always
    env_file:
      - ./server/.env.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["sh", "./migration.sh"]

  client:
    build:
      context: ./client
    container_name: orbit-client
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - server

volumes:
  postgres_data: